import { NextResponse } from 'next/server';
import * as fs from 'fs';
import * as path from 'path';

const VAULT_PATH = process.env.VAULT_PATH || path.join(process.cwd(), '..');
const NERVE_CENTER = path.join(process.cwd(), '..', '..', 'nerve_center');

interface Task {
  id: string;
  title: string;
  status: string;
  priority: string;
  due_date?: string;
}

interface Contact {
  id: string;
  name: string;
  type: string;
  lead_value?: number;
  lead_stage?: string;
}

interface Invoice {
  id: string;
  type: string;
  status: string;
  line_items: Array<{ quantity: number; unit_price: number }>;
}

function loadJson<T>(filePath: string): T[] {
  try {
    if (fs.existsSync(filePath)) {
      return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
    }
  } catch (error) {
    console.error(`Error loading ${filePath}:`, error);
  }
  return [];
}

function calcTotal(invoice: Invoice): number {
  return (invoice.line_items || []).reduce(
    (sum, item) => sum + (item.quantity || 0) * (item.unit_price || 0),
    0
  );
}

export async function POST() {
  try {
    const timestamp = new Date();
    const dateStr = timestamp.toISOString().split('T')[0];
    const weekStart = new Date(timestamp);
    weekStart.setDate(weekStart.getDate() - 7);

    // Load data
    const tasks = loadJson<Task>(path.join(NERVE_CENTER, 'projects', 'tasks.json'));
    const contacts = loadJson<Contact>(path.join(NERVE_CENTER, 'crm', 'contacts.json'));
    const invoices = loadJson<Invoice>(path.join(NERVE_CENTER, 'finances', 'invoices.json'));

    // Calculate metrics
    const completedTasks = tasks.filter(t => t.status === 'completed').length;
    const inProgressTasks = tasks.filter(t => t.status === 'in_progress').length;
    const todoTasks = tasks.filter(t => t.status === 'todo').length;
    const blockedTasks = tasks.filter(t => t.status === 'blocked').length;

    const overdueTasks = tasks.filter(t => {
      if (!t.due_date || t.status === 'completed') return false;
      return new Date(t.due_date) < timestamp;
    });

    const highPriorityTasks = tasks.filter(t => t.priority === 'high' && t.status !== 'completed');

    // Revenue calculations
    const sentInvoices = invoices.filter(i => i.type === 'sent');
    const paidInvoices = sentInvoices.filter(i => i.status === 'paid');
    const unpaidInvoices = sentInvoices.filter(i => i.status !== 'paid' && i.status !== 'cancelled');

    const totalRevenue = paidInvoices.reduce((sum, i) => sum + calcTotal(i), 0);
    const outstandingAR = unpaidInvoices.reduce((sum, i) => sum + calcTotal(i), 0);

    // Pipeline
    const leads = contacts.filter(c => c.type === 'lead' && c.lead_stage !== 'lost' && c.lead_stage !== 'won');
    const pipelineValue = leads.reduce((sum, c) => sum + (c.lead_value || 0), 0);

    // Generate briefing content
    const briefing = `---
generated: ${timestamp.toISOString()}
period: ${weekStart.toISOString().split('T')[0]} to ${dateStr}
type: ceo_briefing
---

# CEO Briefing - ${timestamp.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}

## Executive Summary

${overdueTasks.length > 0 || blockedTasks > 0
  ? '**Attention Required:** There are tasks that need immediate attention.'
  : 'All systems operational. Tasks are on track.'}

## Task Overview

| Metric | Count |
|--------|-------|
| Completed | ${completedTasks} |
| In Progress | ${inProgressTasks} |
| To Do | ${todoTasks} |
| Blocked | ${blockedTasks} |
| **Overdue** | ${overdueTasks.length} |

${overdueTasks.length > 0 ? `
### Overdue Tasks
${overdueTasks.map(t => `- [ ] **${t.title}** (Due: ${t.due_date})`).join('\n')}
` : ''}

${highPriorityTasks.length > 0 ? `
### High Priority Items
${highPriorityTasks.map(t => `- [ ] ${t.title} - ${t.status}`).join('\n')}
` : ''}

## Financial Summary

| Metric | Amount |
|--------|--------|
| Revenue (Paid) | $${totalRevenue.toLocaleString()} |
| Outstanding AR | $${outstandingAR.toLocaleString()} |
| Pipeline Value | $${pipelineValue.toLocaleString()} |

## CRM Overview

- **Total Contacts:** ${contacts.length}
- **Active Leads:** ${leads.length}
- **Pipeline Value:** $${pipelineValue.toLocaleString()}

## Recommendations

${overdueTasks.length > 0 ? '1. **Address overdue tasks immediately** - Review and update status or extend deadlines.\n' : ''}
${blockedTasks > 0 ? '2. **Resolve blocked items** - Identify and remove blockers for stalled tasks.\n' : ''}
${outstandingAR > 1000 ? '3. **Follow up on outstanding invoices** - AR exceeds $1,000.\n' : ''}
${leads.length > 5 ? '4. **Nurture leads** - Multiple leads in pipeline need attention.\n' : ''}
${!overdueTasks.length && !blockedTasks && outstandingAR <= 1000 ? '- All metrics are within acceptable ranges. Keep up the good work!\n' : ''}

---
*Generated by AI Employee v2.0*
*Next briefing scheduled: ${new Date(timestamp.getTime() + 7 * 24 * 60 * 60 * 1000).toLocaleDateString()}*
`;

    // Save briefing
    const briefingsPath = path.join(VAULT_PATH, 'Business', 'CEO_Briefings');
    if (!fs.existsSync(briefingsPath)) {
      fs.mkdirSync(briefingsPath, { recursive: true });
    }

    const briefingFile = path.join(briefingsPath, `${dateStr}_CEO_Briefing.md`);
    fs.writeFileSync(briefingFile, briefing);

    // Log the action
    const logsPath = path.join(VAULT_PATH, 'Logs');
    if (!fs.existsSync(logsPath)) {
      fs.mkdirSync(logsPath, { recursive: true });
    }
    const logFile = path.join(logsPath, `daily_${dateStr}.log`);
    fs.appendFileSync(logFile, `[${timestamp.toISOString()}] [INFO] CEO Briefing generated: ${briefingFile}\n`);

    return NextResponse.json({
      success: true,
      briefing: `Generated CEO Briefing for ${dateStr}\n\n**Highlights:**\n- ${completedTasks} tasks completed\n- $${totalRevenue.toLocaleString()} revenue\n- ${overdueTasks.length} overdue items`,
      file: briefingFile,
    });
  } catch (error) {
    console.error('Briefing API error:', error);
    return NextResponse.json(
      { error: 'Failed to generate briefing' },
      { status: 500 }
    );
  }
}
